// ─── CURRICULUM DATA ─────────────────────────────────────────────────────
// Each day includes: bpm (recommended entrainment tempo) and scaffold level
// is derived from day number: 1-10 = full, 11-20 = reduced, 21-30 = minimal

export const adultCurriculum = [
  { day:1,  title:"Gentle Vocal Onsets",            tag:"Foundation",      bpm:60,
    strategy:"Begin each vowel-initial syllable with a quiet, breathy /h/ airstream. Let the vocal cords fold together softly, like two feathers touching rather than two palms clapping.",
    prompt:"Practice this phrase: 'Over the horizon, the evening settles easily.' Notice how each word glides into the next without any hard beginnings." },
  { day:2,  title:"Airflow Continuity",              tag:"Foundation",      bpm:60,
    strategy:"Maintain a gentle, uninterrupted stream of air throughout each sentence. Think of your breath as a continuous river — never a series of ponds.",
    prompt:"'Always allow an easy, open air current to carry each syllable along to the next one in every phrase.'" },
  { day:3,  title:"Slow Articulatory Rate",          tag:"Pacing",          bpm:60,
    strategy:"Halve your speaking rate intentionally. Touch each articulatory landmark — lips, tongue, teeth — with awareness and zero urgency.",
    prompt:"'Moving… slowly… and… deliberately… is… not… weakness. It… is… precision.' (Full slow rate — 1 word per 2 seconds.)" },
  { day:4,  title:"Easy Vowel Extension",            tag:"Pacing",          bpm:65,
    strategy:"Stretch the nucleus vowel of each stressed syllable to 1.5× its natural length. The consonants can be brief; the vowel is the foundation.",
    prompt:"'Liiight. Oooopen. Eaaasy. Flowing — each vowel becomes a long, comfortable room you can rest inside.'" },
  { day:5,  title:"Light Articulatory Contact",      tag:"Precision",       bpm:65,
    strategy:"All tongue-to-palate and lip closures should be feather-light. Imagine pressing two soap bubbles together without popping them.",
    prompt:"'People passing pathways pause briefly before picking up pleasant, playful patterns once more.'" },
  { day:6,  title:"Proprioceptive Awareness",        tag:"Precision",       bpm:65,
    strategy:"Before speaking, do a silent body scan: relax jaw, lower shoulders, unclench hands. Speech begins in the body, not just the mouth.",
    prompt:"Close eyes, scan body, breathe in, exhale — then speak: 'I am calm, clear, and in control of my voice.'" },
  { day:7,  title:"Phrase Boundary Breathing",       tag:"Structure",       bpm:70,
    strategy:"Insert a gentle breath pause at every comma and period. Never push past a natural breath boundary in search of fluency.",
    prompt:"'The summit, (breath) while distant, (breath) remains within reach. (breath) One measured step, (breath) then another.'" },
  { day:8,  title:"Prolonged Vowel Stretching",      tag:"Shaping",         bpm:70,
    strategy:"Double down on vowel prolongation. Practice the 'stretched slingshot': pull vowels long, then release consonants smoothly without snapping them forward.",
    prompt:"'L-i-i-g-h-t-l-y touching the keys. M-a-a-k-i-n-g each word flow continuously into the very next phrase sequence.'" },
  { day:9,  title:"Cancellation Practice",           tag:"Modification",    bpm:70,
    strategy:"When a disfluency occurs, finish the word, pause, then consciously reattempt it using a gentle onset. No punishment — only revision.",
    prompt:"Read aloud. If a stutter occurs, pause fully, breathe, then say the word again slowly and smoothly before continuing." },
  { day:10, title:"Pull-Out Technique",              tag:"Modification",    bpm:75,
    strategy:"When you feel a block starting, do not force through it. Consciously slow your articulatory movement, drop jaw tension, and ease out the back end of the word.",
    prompt:"'S—— (feel tension, relax jaw, ease out) —sliding smoothly into the baseline of every spoken word structure.'" },
  { day:11, title:"Preparatory Sets",                tag:"Modification",    bpm:75,
    strategy:"Before a feared word, mentally pre-shape the articulators into a gentle, relaxed configuration. 'Set up' the easy production before speaking.",
    prompt:"Preview each underlined word silently: 'Confidence comes from consistent, careful, conscious daily practice.'" },
  { day:12, title:"Freezing and Holding",            tag:"Desensitization", bpm:75,
    strategy:"On purpose, enter a voluntary stutter. Hold it for 3 seconds. Study it objectively. Then exit smoothly. Remove its power by examining it.",
    prompt:"Select any word and intentionally prolong its first sound for 3 full seconds, then release calmly and continue reading." },
  { day:13, title:"Feared Word Hierarchy",           tag:"Desensitization", bpm:80,
    strategy:"List words from least to most feared. Practice each one, starting with easy ones, moving toward your top-five feared words.",
    prompt:"Speak 5 words from your personal difficulty list, using gentle onset and pull-out on every one, regardless of fluency outcome." },
  { day:14, title:"Telephone Simulation",            tag:"Application",     bpm:80,
    strategy:"Simulate a phone call scenario. Phone calls remove visual cues, increasing anxiety. Apply full toolkit: onset, pacing, and breathing.",
    prompt:"Role-play: 'Hello, this is (name). I am calling to (reason). Could you please (request)? Thank you for your time.'" },
  { day:15, title:"Situational Transfer — Low Stress",tag:"Transfer",       bpm:80,
    strategy:"Apply all techniques in a low-stakes real-world interaction: ordering coffee, greeting a neighbor, reading aloud to a friend.",
    prompt:"Script a real interaction you'll have today. Write it out, rehearse it here, then execute it. Report back tomorrow." },
  { day:16, title:"Active Mid-Block Pull-Outs",      tag:"Modification",    bpm:85,
    strategy:"When you encounter a block mid-word, do not force forward. Slow down, consciously drop your lower jaw tension, and glide through the rest.",
    prompt:"'S———(catch tension, open jaw, drop pressure)——sliding smoothly down into the baseline of each word structure.'" },
  { day:17, title:"Reading Aloud — Slow Pace",       tag:"Pacing",          bpm:85,
    strategy:"Read any paragraph at half your natural speed with sustained gentle onsets. Record yourself and compare to yesterday's recording.",
    prompt:"Read the following at deliberate, slow pace: 'The art of fluent speech is not speed — it is the seamless connection between intention and sound.'" },
  { day:18, title:"Monologue Practice",              tag:"Application",     bpm:85,
    strategy:"Speak unscripted for 2 minutes about any topic. Apply all techniques simultaneously. Fluency is secondary — technique is primary.",
    prompt:"Speak freely for 2 minutes about: 'A place I find peaceful.' Focus on airflow and gentle onsets throughout." },
  { day:19, title:"Cognitive Load Resistance",       tag:"Advanced",        bpm:90,
    strategy:"Maintain technique while counting backwards from 100 in 7s in your head as you speak. This mimics real-world cognitive interference.",
    prompt:"While counting backwards by 7 mentally: 'I maintain conscious control over my speech mechanisms regardless of mental load.'" },
  { day:20, title:"Partner Interruption Drill",      tag:"Advanced",        bpm:90,
    strategy:"Have a partner or record yourself, then replay and interrupt playback randomly. Resume smoothly using preparatory sets.",
    prompt:"Practice recovery: If interrupted mid-sentence, pause fully, reset breath, then resume from a natural phrase boundary — never force." },
  { day:21, title:"Naturalness Integration",         tag:"Naturalness",     bpm:90,
    strategy:"Begin reducing over-extension. Move toward natural prosody while maintaining zero hard contacts and gentle onsets.",
    prompt:"Read this at natural pace with only gentle onset and airflow as active tools: 'Good morning. The weather looks clear and bright today.'" },
  { day:22, title:"Rate Modulation",                 tag:"Naturalness",     bpm:95,
    strategy:"Practice speaking at slow, medium, and fast rates — applying techniques at each. Real speech varies rate; your toolkit must transfer across speeds.",
    prompt:"Say this sentence at 3 different speeds. Slow: 5 sec. Medium: 3 sec. Fast: 2 sec: 'Every word I speak is mine to shape and own.'" },
  { day:23, title:"Prosodic Stress Practice",        tag:"Naturalness",     bpm:95,
    strategy:"Natural speech uses emphasis. Practice stressing different words in the same sentence while maintaining technique.",
    prompt:"Stress each bold word in turn: 'I SPEAK with clarity.' / 'I speak WITH clarity.' / 'I speak with CLARITY.'" },
  { day:24, title:"Group Simulation",                tag:"Transfer",        bpm:95,
    strategy:"Simulate speaking to a group — stand up, project, maintain eye contact with a fixed point. Apply your full toolkit at normal volume.",
    prompt:"Deliver this as if addressing 10 people: 'I want to share something important. (pause) I have been working on my voice, and today it belongs to me.'" },
  { day:25, title:"Phone — High Stakes Drill",       tag:"Transfer",        bpm:100,
    strategy:"Make one real phone call using full technique. Script it beforehand. Your first fluency transfer beyond the therapy room.",
    prompt:"Script a real call (appointment, question, check-in). Write it, rehearse it here, then make the call. You are ready." },
  { day:26, title:"Emotional Speech Under Load",     tag:"Advanced",        bpm:100,
    strategy:"Practice speaking on emotionally charged topics. Emotion activates the neural loop most strongly. Technique must hold under feeling.",
    prompt:"Talk for 90 seconds about something you genuinely care about. Apply full toolkit. Feel and speak simultaneously — this is mastery." },
  { day:27, title:"Spontaneous Conversation Drill",  tag:"Advanced",        bpm:100,
    strategy:"Engage someone in a 5-minute spontaneous conversation — no script, no agenda. Apply techniques, but prioritize connection over perfection.",
    prompt:"Today's assignment is off-screen. Find a real conversation. Your only job is gentle onset and sustained airflow. Report how it felt." },
  { day:28, title:"Relapse Prevention Map",          tag:"Maintenance",     bpm:100,
    strategy:"Identify your three highest-risk situations. Build an explicit micro-plan for each. Relapse is a data point, not a failure.",
    prompt:"Write three personal high-risk scenarios and one technique response for each. Recite each scenario + response aloud, slowly and clearly." },
  { day:29, title:"Reflection and Integration",      tag:"Maintenance",     bpm:100,
    strategy:"Review your progress. Acknowledge what changed. Name two techniques you will carry permanently. Celebrate the work done.",
    prompt:"Speak freely for 3 minutes: 'On Day 1 I was… Today I am… The one thing I will always carry with me is…'" },
  { day:30, title:"Cognitive Noise Thresholds",      tag:"Mastery",         bpm:100,
    strategy:"Maintain uninterrupted vocalization even when sensory disruptions, emotional noise, or external patterns challenge your focus. This is full integration.",
    prompt:"'I maintain autonomous control over my physical speech mechanisms regardless of internal pressure or external environment. My voice is mine.'" }
];

export const kidsCurriculum = [
  { day:1,  title:"The Turtle Talk Journey",     tag:"Start Here!", bpm:55,
    strategy:"Speak like a wise old turtle who never rushes. Give every single word its very own stepping stone. No word is in a hurry!",
    prompt:"'The. fat. cat. sat. on. the. bright. orange. mat.' (Touch each word like a separate stepping stone across a pond!)" },
  { day:2,  title:"Magic Bubble Breaths",        tag:"Breathing",   bpm:55,
    strategy:"Before each sentence, blow out a tiny invisible magic bubble with your mouth. This sets up the perfect airflow for smooth, easy words!",
    prompt:"Blow bubble → then say: 'I blew a big beautiful bubble that bounced over the bright blue bushes beyond the barn.'" },
  { day:3,  title:"The Slow-Mo Superhero",       tag:"Pacing",      bpm:60,
    strategy:"Slow-motion heroes are the most powerful! When we slow down our words, we give our voice superpowers of smoothness.",
    prompt:"'Sloooow-moooo suuuuperherooooes saaave the daaaaay with caaaalm, cooooool confidence.'" },
  { day:4,  title:"Stretchy Vowel Superpower",   tag:"Pacing",      bpm:60,
    strategy:"Vowels (A, E, I, O, U) are like stretchy superpower bands. The longer you stretch them, the smoother your voice flows!",
    prompt:"'Oooopen your mooouth wiiiide and leeeet the woooords fluuuuw out liiike a riiiiiver.'" },
  { day:5,  title:"The Feather Touch",           tag:"Precision",   bpm:65,
    strategy:"Imagine your lips and tongue are holding a tiny feather between them — so gently that the feather never falls!",
    prompt:"'Pretty purple parrots pick perfectly placed purple petals every pleasant afternoon.' (Feather-light lips on every P!)" },
  { day:6,  title:"The Body Reset Button",       tag:"Calm",        bpm:65,
    strategy:"Before speaking, press your invisible reset button: wiggle your fingers, drop your shoulders, take a big belly breath. Now your voice is ready!",
    prompt:"Wiggle hands → drop shoulders → big belly breath → then say: 'I am calm. I am ready. My words come out smooth and strong.'" },
  { day:7,  title:"Story Stepping Stones",       tag:"Structure",   bpm:65,
    strategy:"Every pause in a sentence is like a stepping stone. Jump from stone to stone — don't rush or you might fall in!",
    prompt:"'The dragon, (jump) who loved rainbows, (jump) flew high above the clouds, (jump) looking for the perfect gold treasure below.'" },
  { day:8,  title:"The Magic Copycat Engine",    tag:"Listening",   bpm:70,
    strategy:"Listen carefully to the small echo you hear in your headphones. Your voice and the echo are playing a copycat game. Match the rhythm!",
    prompt:"'Bouncing bubbles blow big bright blue balloons beautifully.' (Copy the echo — stay with its rhythm like a dance partner!)" },
  { day:9,  title:"The Word Redo Game",          tag:"Modification",bpm:70,
    strategy:"If a word gets a little bumpy, that's okay! Just finish it, take a tiny pause, and try the word again smooth and easy. It's just a fun redo!",
    prompt:"If any word feels bumpy during practice: stop, breathe, then say just that word again super-smoothly before continuing." },
  { day:10, title:"The Slow Slide Trick",        tag:"Modification",bpm:70,
    strategy:"When a word feels stuck, don't push — SLIDE! Imagine your tongue is on a slow waterslide. It glides down and out, never rushing or jamming.",
    prompt:"'Sss— (slow slide!) —snakes slither silently through sun-speckled shade.' (Feel the smooth waterslide on every S!)" },
  { day:11, title:"The Ready Position",          tag:"Preparation", bpm:75,
    strategy:"Before a tricky word, take a tiny moment to get your mouth ready — like a sprinter in position before the race. A ready mouth speaks smoothly!",
    prompt:"Practice getting ready: look at each word → mouth shape it silently → then say it aloud with a smooth, easy beginning." },
  { day:12, title:"The Brave Freeze Game",       tag:"Confidence",  bpm:75,
    strategy:"Be SO brave that you can freeze on a sound ON PURPOSE for 3 whole seconds. When you can freeze on command, the freeze loses all its power!",
    prompt:"Pick any word and hold its first sound for 3 seconds on purpose — ssss, llll, mmmm — then slide right through it smoothly!" },
  { day:13, title:"My Tricky Word List",         tag:"Courage",     bpm:75,
    strategy:"Make a list of your tricky words, then practice them using all your superpowers — they're just dragons that haven't been tamed yet.",
    prompt:"Say 5 of YOUR tricky words, one at a time. Use your Turtle Talk, Feather Touch, and Slow Slide on every single one!" },
  { day:14, title:"The Phone Adventure",         tag:"Real World",  bpm:80,
    strategy:"Phone calls are level-up challenges because you can't see the other person's face! Use ALL your tools: breathe, start soft, go slow.",
    prompt:"Practice this phone script: 'Hello! This is (your name). I'm calling because I wanted to (reason). Could you please help me? Thank you!'" },
  { day:15, title:"The Outside Mission",         tag:"Real World",  bpm:80,
    strategy:"Today you go on a REAL WORLD mission! Pick one safe conversation outside this app and try your tools. Even one smooth sentence is a massive win!",
    prompt:"Choose your mission: order something, ask a question, say hello to someone new. Then come back and tell the story of your adventure!" },
  { day:16, title:"The Elastic Band Technique",  tag:"Shaping",     bpm:80,
    strategy:"When a word tries to pop out too fast, imagine an elastic band holding it gently — it can still come out, just sloooowly and smoothly!",
    prompt:"'Eeeelastic bands help slooow words reach their destination smooothly every single time.'" },
  { day:17, title:"Read It Slow-Mo",             tag:"Pacing",      bpm:85,
    strategy:"Pick any book, any paragraph. Read it at HALF your normal speed. Feel how much easier the words come when they're not being rushed!",
    prompt:"Read any 3 sentences from your favourite book right now — but in slow-motion superhero mode. Every word gets its own moment." },
  { day:18, title:"The Story Explorer",          tag:"Adventure",   bpm:85,
    strategy:"Tell a story about ANYTHING — a dream, a game, an adventure. Don't worry about perfect — just keep the words flowing like a river!",
    prompt:"Tell a 2-minute story about: 'My favourite place in the whole world.' Use Turtle Talk and Bubble Breaths as you go!" },
  { day:19, title:"Noisy Room Challenge",        tag:"Advanced",    bpm:85,
    strategy:"Real life is loud! Practice today with some background noise on so your brain learns to stay calm and smooth even when things get distracting.",
    prompt:"With soft music playing: 'My voice stays smooth and strong even when things are busy and loud all around me.'" },
  { day:20, title:"The Surprise Interruption",   tag:"Advanced",    bpm:90,
    strategy:"If you get interrupted, that's okay! Pause, breathe like a turtle, and start the sentence again from the beginning. Interruptions are just little detours.",
    prompt:"Practice pausing + restarting: 'The most important thing I want to say is— (pause, breathe) — The most important thing I want to say is that I can do this!'" },
  { day:21, title:"Natural Flow Mode",           tag:"Naturalness", bpm:90,
    strategy:"Today is about sounding like YOU — not a turtle, not a superhero, just you. Use your tools quietly in the background, like a secret superpower.",
    prompt:"Say the following at a natural, easy pace, just being you: 'Good morning. I had a great idea today. I think you're going to like it.'" },
  { day:22, title:"Speed Level Up!",             tag:"Naturalness", bpm:90,
    strategy:"Time to practice at DIFFERENT speeds — slow, medium, fast — like a video game with speed levels. You should be able to use your tools at ALL levels!",
    prompt:"Say this sentence slow (5 sec), medium (3 sec), then fast (2 sec): 'Every word I say belongs to me and I say it well.'" },
  { day:23, title:"The Feeling Speaker",         tag:"Expression",  bpm:95,
    strategy:"When you speak with FEELING — excitement, happiness, silliness — your whole brain gets involved and stuttering takes a backseat!",
    prompt:"Say this with as much EXCITEMENT as possible: 'I just discovered the most amazing thing in the entire universe and I absolutely HAVE to tell you about it!'" },
  { day:24, title:"The Stage Voice",             tag:"Transfer",    bpm:95,
    strategy:"Imagine you're on a stage performing for 100 people. Stand tall, take a big breath, and speak like your voice fills the whole room.",
    prompt:"Stand up! Say this to the room: 'I have something important to tell you. I have been learning how to use my voice. And it is getting stronger every day.'" },
  { day:25, title:"The Real Phone Call",         tag:"Transfer",    bpm:95,
    strategy:"This is the real thing! Make one actual phone call today. Your toolkit is ready. You are ready.",
    prompt:"Write out your phone script, rehearse it twice here, then MAKE THE CALL. When you come back: tell me how it went in the journal!" },
  { day:26, title:"Heart Talk",                  tag:"Feelings",    bpm:100,
    strategy:"Talk about something that truly matters to you — your pet, your favourite game, your best memory. When your heart is in it, your voice follows.",
    prompt:"Tell me about something you love with your WHOLE heart — speak for 90 seconds without stopping. Let the love carry the words." },
  { day:27, title:"Free Conversation Quest",     tag:"Real World",  bpm:100,
    strategy:"Today's whole mission is OFF this app. Have a real 5-minute conversation with anyone, about anything, using your tools.",
    prompt:"Off-screen adventure! Find someone to chat with for 5 minutes. ANY topic. When you return, log how it felt: easy, medium, or adventurous?" },
  { day:28, title:"My Fluency Shield",           tag:"Maintenance", bpm:100,
    strategy:"YOUR fluency shield has 3 powers on it — your 3 best tools. Name them, claim them, they're yours forever.",
    prompt:"Name your 3 favourite tools aloud: 'My three fluency superpowers are: (1)___, (2)___, and (3)___. I will use them every day forever!'" },
  { day:29, title:"The Celebration Speech",      tag:"Reflection",  bpm:100,
    strategy:"You have done something truly AMAZING. Today you get to look back and feel proud. Your voice grew. You grew. This is worth celebrating!",
    prompt:"Say out loud: 'On Day 1 I felt… Now on Day 29 I feel… The superpower I am most proud of is…' Take your time. You earned this." },
  { day:30, title:"The Brave Story Explorer",    tag:"Mastery",     bpm:100,
    strategy:"You are now a full Fluency Explorer! Use ALL your tools and tell your greatest adventure story yet!",
    prompt:"Tell your best story: An astronaut, a dragon, a time traveller — any hero who found their voice and used it to save the day. Go!" }
];
